// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> generateUrlByArea(
        {String? area,
        required String tag,
        required String language,
        dynamic hint}) =>
    RustLib.instance.api.generateUrlByArea(
        area: area, tag: tag, language: language, hint: hint);

Future<String> generateUrlByGalleryId({required int galleryId, dynamic hint}) =>
    RustLib.instance.api
        .generateUrlByGalleryId(galleryId: galleryId, hint: hint);
