// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Int32List> getDataFromUrl(
        {required String nozomiAddress, dynamic hint}) =>
    RustLib.instance.api
        .getDataFromUrl(nozomiAddress: nozomiAddress, hint: hint);

Future<GalleryInfo> getGalleryDataFromUrl(
        {required String galleryUrl, dynamic hint}) =>
    RustLib.instance.api
        .getGalleryDataFromUrl(galleryUrl: galleryUrl, hint: hint);
