[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
byteorder = "1.5.0"
reqwest = "0.11.24"
flutter_rust_bridge = "=2.0.0-dev.22"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
