// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

Future<Int32List> getGalleryIdsFromNozomi(
        {String? area,
        required String tag,
        required String language,
        dynamic hint}) =>
    RustLib.instance.api.getGalleryIdsFromNozomi(
        area: area, tag: tag, language: language, hint: hint);

Future<GalleryInfo> getGalleryDataFromId(
        {required int galleryId, dynamic hint}) =>
    RustLib.instance.api.getGalleryDataFromId(galleryId: galleryId, hint: hint);
